-- =====================================================================
-- AmarShohor — remove the demo data made by seed_heatmap.sql
--
-- Run in the Supabase SQL Editor of the AmarShohor project (check the
-- project name at the top left first). Safe to run more than once.
--
-- What it removes: the ~80 fake "Demo citizen" accounts (email ending in
-- @seed.amarshohor.test) and everything attached to them: their ~8,000
-- "[demo]" issues and those issues' votes, comments, events and
-- notifications. Real accounts and real reports are not touched.
--
-- Why: besides odd numbers on the feed, the fake reporters count as
-- "active neighbours", which switches off the lower validation threshold
-- for quiet areas, so real reports were much harder to validate.
-- =====================================================================

-- 1. Preview: what will be deleted, and what stays.
select
  (select count(*) from auth.users where email like '%@seed.amarshohor.test')  as demo_accounts,
  (select count(*) from public.issues i join auth.users u on u.id = i.reporter_id
    where u.email like '%@seed.amarshohor.test')                                as demo_issues,
  (select count(*) from public.issues i join auth.users u on u.id = i.reporter_id
    where u.email not like '%@seed.amarshohor.test')                            as real_issues_kept;

-- 2. Delete. Removing the accounts cascades to their profiles and issues,
--    and from the issues to votes, comments, events, media rows and so on.
begin;
delete from auth.users where email like '%@seed.amarshohor.test';
-- Any "[demo]" issue left over from an older seed run under another account.
delete from public.issues where title like '[demo]%' and description like 'Generated by seed_heatmap.sql%';
commit;

-- 3. Check: both counts should be 0, and real_issues_kept the same as above.
select
  (select count(*) from auth.users where email like '%@seed.amarshohor.test') as demo_accounts_left,
  (select count(*) from public.issues where title like '[demo]%')            as demo_issues_left,
  (select count(*) from public.issues)                                       as real_issues_kept;
